# Generated by Django 3.2.9 on 2021-12-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oex', '0006_auto_20211215_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericstringtaggeditem',
            name='is_strike_through',
            field=models.BooleanField(default=False),
        ),
    ]
