# Generated by Django 3.2.9 on 2021-12-16 05:01

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('oex', '0008_auto_20211215_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='display_order',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='published_at',
            field=model_utils.fields.MonitorField(blank=True, default=None, monitor='status', null=True, when={'published'}),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='draft', max_length=100, no_check_for_status=True),
        ),
    ]
