# Generated by Django 3.2.9 on 2021-12-16 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oex', '0010_auto_20211216_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workspaceposition',
            old_name='name',
            new_name='title',
        ),
    ]
