# Generated by Django 3.2.9 on 2021-12-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oex', '0012_rename_display_space_workspaceposition_work_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=9, null=True),
        ),
    ]
