# Generated by Django 3.2.9 on 2022-02-27 09:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ks_shared.django.model_utils
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('oex', '0013_alter_work_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='belong_to',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='user', max_length=100, no_check_for_status=True),
        ),
        migrations.AddField(
            model_name='space',
            name='accepted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='accepted_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_by', related_query_name='accepted_by', to='user.user'),
        ),
        migrations.AddField(
            model_name='space',
            name='contact_cellphone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='space',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='space',
            name='space_area',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='space',
            name='storekeeper',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storekeeper', related_query_name='storekeeper', to='user.user'),
        ),
        migrations.AddField(
            model_name='space',
            name='verify_status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='apply', max_length=100, no_check_for_status=True),
        ),
        migrations.CreateModel(
            name='SpacePicture',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.CharField(default=ks_shared.django.model_utils.generate_uuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('category', model_utils.fields.StatusField(choices=[('outside', 'outside'), ('inside', 'inside'), ('other', 'other')], default='outside', max_length=100, no_check_for_status=True)),
                ('file', models.FileField(upload_to=ks_shared.django.model_utils.upload_to)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oex.space')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
