# Generated by Django 3.2.13 on 2022-05-05 10:43

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('oex', '0014_auto_20220227_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='accepted_at',
            field=model_utils.fields.MonitorField(blank=True, default=None, monitor='verify_status', null=True, when={'accepted'}),
        ),
        migrations.AlterField(
            model_name='space',
            name='verify_status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='pending', max_length=100, no_check_for_status=True),
        ),
    ]
