# Generated by Django 3.2.13 on 2022-07-09 21:14

from django.db import migrations, models
import ks_shared.django.model_utils


class Migration(migrations.Migration):

    dependencies = [
        ('oex', '0015_auto_20220505_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spacepicture',
            name='file',
        ),
        migrations.AddField(
            model_name='spacepicture',
            name='pic',
            field=models.ImageField(default='', upload_to=ks_shared.django.model_utils.upload_to),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='space',
            name='cover',
            field=models.ImageField(blank=True, default=None, help_text='670 x 380', null=True, upload_to=ks_shared.django.model_utils.upload_to),
        ),
        migrations.AlterField(
            model_name='space',
            name='cover_s',
            field=models.ImageField(blank=True, default=None, help_text='190 x 190', null=True, upload_to=ks_shared.django.model_utils.upload_to),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='cover',
            field=models.ImageField(help_text='555 x 380', upload_to=ks_shared.django.model_utils.upload_to),
        ),
    ]
