# Generated by Django 3.2.13 on 2022-07-10 14:52

from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('oex', '0016_auto_20220710_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='accepted_at',
            field=model_utils.fields.MonitorField(blank=True, default=None, monitor='verify_status', null=True, when={'accepted'}),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='accepted_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_exhibitions', to='user.user'),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='rejected_at',
            field=model_utils.fields.MonitorField(blank=True, default=None, monitor='verify_status', null=True, when={'rejected'}),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='rejected_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_exhibitions', to='user.user'),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='rejected_reason',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='verify_status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='pending', max_length=100, no_check_for_status=True),
        ),
        migrations.AddField(
            model_name='space',
            name='rejected_at',
            field=model_utils.fields.MonitorField(blank=True, default=None, monitor='verify_status', null=True, when={'rejected'}),
        ),
        migrations.AddField(
            model_name='space',
            name='rejected_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_spaces', to='user.user'),
        ),
        migrations.AddField(
            model_name='space',
            name='rejected_reason',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='space',
            name='accepted_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_spaces', to='user.user'),
        ),
    ]
