# Generated by Django 3.2.13 on 2022-07-10 22:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ks_shared.django.model_utils
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('oex', '0017_auto_20220710_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageThread',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.CharField(default=ks_shared.django.model_utils.generate_uuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('type', models.CharField(default='sys', max_length=20)),
                ('object_type', models.CharField(blank=True, default='', max_length=20)),
                ('object_id', models.CharField(blank=True, default='', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('latest_msg_at', models.DateTimeField(blank=True, null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_received_thread', to='user.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_send_thread', to='user.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.CharField(default=ks_shared.django.model_utils.generate_uuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=255)),
                ('content', models.TextField(default='')),
                ('msg_type', models.CharField(default='text', max_length=20)),
                ('object_type', models.CharField(blank=True, default='', max_length=20)),
                ('object_id', models.CharField(blank=True, default='', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='oex.messagethread')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
