# Generated by Django 3.2.13 on 2022-07-10 23:20

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('oex', '0018_message_messagethread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='msg_type',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='text', max_length=100, no_check_for_status=True),
        ),
    ]
