# Generated by Django 3.2.13 on 2022-07-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oex', '0019_alter_message_msg_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
