# Generated by Django 3.2.9 on 2021-12-06 09:08

from django.db import migrations, models
import django.utils.timezone
import ks_shared.django.model_utils
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', models.CharField(default=ks_shared.django.model_utils.generate_uuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('value', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', models.CharField(default=ks_shared.django.model_utils.generate_uuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('openid', models.CharField(blank=True, db_index=True, max_length=30)),
                ('unionid', models.CharField(blank=True, db_index=True, default=None, max_length=30, null=True)),
                ('cellphone', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('email', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('birthday', models.DateField(blank=True, default=None, null=True)),
                ('gender', model_utils.fields.StatusField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', max_length=100, no_check_for_status=True)),
                ('avatar', models.ImageField(blank=True, default=None, null=True, upload_to=ks_shared.django.model_utils.upload_to_without_rename)),
                ('city', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('province', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('country', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('language', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('avatar_url', models.CharField(blank=True, default=None, help_text='wxa avatar url', max_length=255, null=True)),
                ('last_update_wxa_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('wxa_json', models.JSONField(blank=True, default=dict)),
                ('utm_campaign', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('utm_source', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('role', model_utils.fields.StatusField(choices=[('user', 'User'), ('storekeeper', 'storekeeper')], default='user', max_length=100, no_check_for_status=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
